Timeout = 25
Homework = "Tema1"
EmailAddress = "mihai.lica.pura@gmail.com"
Password = "gdht65Tyh^ty&&"
EmailServerAddress = "smtp.gmail.com"
EmailServerPort = 587
ImapServerAddress = "imap.gmail.com"
Subject = "LF.Tema1.*.*"
ZipFormat = "(E213[A-D]).*.*.zip"
GradeEmailSubject = "Nota Tema Limbaje Formale"
GradeEmailBody = "Felicitari! Ati primit nota: "
SheetsScopes = 'https://www.googleapis.com/auth/spreadsheets'
SheetsSecretFile = 'client_id.json'
SheetsApplicationName = 'Verificator teme'
SheetsKey = 'AIzaSyA6kq1zFm7yPVYAxOT5Z2DG_yyJ_VlDo8U'
SheetsId = '1bxkc-0ls2Pc3dEiitXOoURgg3KqmV7j1uWuuWjZiZFw'
BuildString = "csc /out:\"tema1.exe\" /recurse:\".\\Proiect\\*.cs\""
ExeFilename = "tema1.exe"
AbsolutePath = "C:\\Users\\Evaluator\\Desktop\\CheckerDir\\"
RelativeDownloadPath = "Downloads\\"
RelativeCheckerPath = "checker\\"