ConnectionServerMail = "Eroare la conectarea la serverul de email"
SendEmail = "Eroare la trimiterea emailului pentru "
ZipExtract = "Nu se poate extrage din arhiva"
Reported = "Am trimis EROARE studentului "
NotRan = "Verifica formatul si reincearca"
NotCompiled = "Programul nu a putut fi compilat"
WrongMode = "Primul parametru este incorect!\nIncearca \"exe\",\"source\" sau \"zip\"!"
WrongHomework = "Al doilea parametru este incorect!\nIncearca \"translator\", \"cypher\" sau \"regex\""
WrongFile = "Fisierul mentionat prin al treilea parametru nu exista!"
WrongArgumentCount = "Numarul de parametri este incorcect! Incearca o comanda de urmatorul fel=\npython offline_checker.py mod tema fisier"
WrongZipName = "Arhiva .zip nu este denumita corespunzator. Verifica formatul specificat!"
BuildFailed = "A intervenit o eroare la compilarea programului.\nVerificati ca ati urmarit toti pasii din readme.txt!"
DefaultText = "A intervenit o eroare!"
EmailSubject = "Email error!"
WrongSubject = "Subiectul emailului este incorect!"
MissingArchive = "Nu exista o arhiva atasata emailului!"
